### ISSUE TITLE
Main Movie List

### ISSUE THREAD

**Issue by drew-harris** [drew-harris/db-gui-team-1#49]
The main page will need to have a big list of movies

Features needed: 
Searching
Sorting
Pagination/Infinite List

Only 1 endpoint is needed to create this but it will be a more complicated endpoint

**Comment by drew-harris** [comment]
Closes #41 
Closes #37 
Closes #36 
Closes #35 
Closes #33 
Closes #30 
Closes #26 
Closes #21 
Closes #7
Closes #6 
Closes #2 
Closes #1

**Comment by drew-harris** [comment]
# Task List
### Backend
 - [x] Create Zod schema for api endpoint
 - [x] Create API Endpoint that allows search, filter, sort, pages (using query params)
 - [x] Make endpoint only return top 100 moves by tmdb popularity if user not logged in
 - [ ] Document endpoint thoroughly
 - [x] Create zod schema that describes sorting and filtering options (ask Drew if confused by this) 
 
### Frontend
 - [x] Setup React Query
 - [x] Create movie display component to show movie in list (clicking these will eventually go to movie page
 - [ ] Create custom input, dropdown, select components
 - [ ] Create pagination component, and custom hook
