### ISSUE TITLE
Reviews and Ratings

### ISSUE THREAD

**Issue by drew-harris** [drew-harris/db-gui-team-1#50]
Navigating to a movie's page will allow the user to view reviews. Logged in users will be able to leave a review.

**Comment by drew-harris** [comment]
Closes #3 
Closes #4 
Closes #32
Closes #42 
Closes #46 
Closes #45 
Closes #44 
Closes #43

**Comment by drew-harris** [comment]
# Task List

## Backend
 - [ ] Create GET endpoint for list of reviews based off movie id in url param
 - [ ] Create POST endpoint for leaving a review that parses jwt cookie (user must be logged in)
 - [ ] Create GET endpoint for average rating based off movie id in url param
 - [ ] Create POST endpoint for leaving rating 
        * Must not allow users to leave rating multiple times!
 - [ ] Create zod schema for ^^ all endpoints above 
 - [ ] Document endpoints
